//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoCaoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wishlist
    {
        public int id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> productId { get; set; }
        public string productName { get; set; }
        public string price { get; set; }
        public string image { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
